#pragma once
#include <stdio.h>

typedef struct qcs_simulator qcs_simulator;
typedef void (*qcs_exception_callback)(char const *message, size_t message_length);

#ifdef __cplusplus
qcs_simulator *qcs_simulator_create_cxx(void);
void qcs_simulator_destroy_cxx(qcs_simulator *sim);
void qcs_simulator_allocate_memory_cxx(qcs_simulator *sim);
void qcs_simulator_dispose_cxx(qcs_simulator *sim);
int qcs_simulator_get_num_procs_cxx(qcs_simulator *sim);
int qcs_simulator_get_proc_num_cxx(qcs_simulator *sim);
int qcs_simulator_get_num_qubits_cxx(const qcs_simulator *sim);
int qcs_simulator_get_num_clbits_cxx(const qcs_simulator *sim);
void qcs_simulator_set_num_qubits_cxx(qcs_simulator *sim, int num_qubits);
void qcs_simulator_set_mapping_cxx(qcs_simulator *sim, const int *perm_p2l, int perm_p2l_count);
void qcs_simulator_set_num_clbits_cxx(qcs_simulator *sim, int num_clbits);
void qcs_simulator_get_clbits_cxx(const qcs_simulator *sim, int *clbits);
void qcs_simulator_get_clbits_string_cxx(const qcs_simulator *sim, char *clbits_string);
void qcs_simulator_reset_cxx(qcs_simulator *sim, int qubit_num);
void qcs_simulator_set_zero_state_cxx(qcs_simulator *sim);
void qcs_simulator_set_sequential_state_cxx(qcs_simulator *sim);
void qcs_simulator_set_flat_state_cxx(qcs_simulator *sim);
void qcs_simulator_set_entangled_state_cxx(qcs_simulator *sim);
void qcs_simulator_set_random_state_cxx(qcs_simulator *sim);
void qcs_simulator_reset_clbits_cxx(qcs_simulator *sim);
void qcs_simulator_reset_measurement_state_cxx(qcs_simulator *sim);
void qcs_simulator_reinitialize_mapping_cxx(qcs_simulator *sim);
void qcs_simulator_gate_global_phase_cxx(qcs_simulator *sim, double theta, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_h_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_x_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_y_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_z_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_s_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_sdg_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_t_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_tdg_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_sx_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rx_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_ry_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rz_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_u4_cxx(qcs_simulator *sim, double theta, double phi, double lambda, double gamma, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_u3_cxx(qcs_simulator *sim, double theta, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_u2_cxx(qcs_simulator *sim, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_u1_cxx(qcs_simulator *sim, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_u_cxx(qcs_simulator *sim, double theta, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_p_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_swap_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_iswap_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_id_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_sxdg_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_r_cxx(qcs_simulator *sim, double theta, double phi, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rxx_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_ryy_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rzz_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rzx_cxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_dcx_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_ecr_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_xx_plus_yy_cxx(qcs_simulator *sim, double theta, double beta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_xx_minus_yy_cxx(qcs_simulator *sim, double theta, double beta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rccx_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
void qcs_simulator_gate_rcccx_cxx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_measure_cxx(qcs_simulator *sim, int qubit_num);
int qcs_simulator_measure_to_clbit_cxx(qcs_simulator *sim, int qubit_num, int clbit_num);
int qcs_simulator_read_cxx(qcs_simulator *sim, int clbit_num);
void qcs_simulator_save_statevector_cxx(qcs_simulator *sim, const char *outfn);
int qcs_simulator_event_create_cxx(qcs_simulator *sim);
void qcs_simulator_event_record_cxx(qcs_simulator *sim, int event_num);
double qcs_simulator_event_get_elapsed_time_cxx(qcs_simulator *sim, int start_event_num, int stop_event_num);
extern "C"
{
#endif

int qcs_set_exception_callback(qcs_exception_callback callback);
int qcs_simulator_create(qcs_simulator **result);
int qcs_simulator_destroy(qcs_simulator *sim);
int qcs_simulator_allocate_memory(qcs_simulator *sim);
int qcs_simulator_dispose(qcs_simulator *sim);
int qcs_simulator_get_num_procs(qcs_simulator *sim, int *result);
int qcs_simulator_get_proc_num(qcs_simulator *sim, int *result);
int qcs_simulator_get_num_qubits(const qcs_simulator *sim, int *result);
int qcs_simulator_get_num_clbits(const qcs_simulator *sim, int *result);
int qcs_simulator_set_num_qubits(qcs_simulator *sim, int num_qubits);
int qcs_simulator_set_mapping(qcs_simulator *sim, const int *perm_p2l, int perm_p2l_count);
int qcs_simulator_set_num_clbits(qcs_simulator *sim, int num_clbits);
int qcs_simulator_get_clbits(const qcs_simulator *sim, int *clbits);
int qcs_simulator_get_clbits_string(const qcs_simulator *sim, char *clbits_string);
int qcs_simulator_reset(qcs_simulator *sim, int qubit_num);
int qcs_simulator_set_zero_state(qcs_simulator *sim);
int qcs_simulator_set_sequential_state(qcs_simulator *sim);
int qcs_simulator_set_flat_state(qcs_simulator *sim);
int qcs_simulator_set_entangled_state(qcs_simulator *sim);
int qcs_simulator_set_random_state(qcs_simulator *sim);
int qcs_simulator_reset_clbits(qcs_simulator *sim);
int qcs_simulator_reset_measurement_state(qcs_simulator *sim);
int qcs_simulator_reinitialize_mapping(qcs_simulator *sim);
int qcs_simulator_gate_global_phase(qcs_simulator *sim, double theta, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_h(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_x(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_y(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_z(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_s(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_sdg(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_t(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_tdg(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_sx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_ry(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rz(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_u4(qcs_simulator *sim, double theta, double phi, double lambda, double gamma, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_u3(qcs_simulator *sim, double theta, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_u2(qcs_simulator *sim, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_u1(qcs_simulator *sim, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_u(qcs_simulator *sim, double theta, double phi, double lambda, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_p(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_swap(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_iswap(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_id(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_sxdg(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_r(qcs_simulator *sim, double theta, double phi, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rxx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_ryy(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rzz(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rzx(qcs_simulator *sim, double theta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_dcx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_ecr(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_xx_plus_yy(qcs_simulator *sim, double theta, double beta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_xx_minus_yy(qcs_simulator *sim, double theta, double beta, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rccx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_gate_rcccx(qcs_simulator *sim, const int *target_qubit_num_list, int target_qubit_num_count, const int *negctrl_qubit_num_list, int negctrl_qubit_num_count, const int *ctrl_qubit_num_list, int ctrl_qubit_num_count);
int qcs_simulator_measure(qcs_simulator *sim, int qubit_num, int *result);
int qcs_simulator_measure_to_clbit(qcs_simulator *sim, int qubit_num, int clbit_num, int *result);
int qcs_simulator_read(qcs_simulator *sim, int clbit_num, int *result);
int qcs_simulator_save_statevector(qcs_simulator *sim, const char *outfn);
int qcs_simulator_event_create(qcs_simulator *sim, int *result);
int qcs_simulator_event_record(qcs_simulator *sim, int event_num);
int qcs_simulator_event_get_elapsed_time(qcs_simulator *sim, int start_event_num, int stop_event_num, double *result);
#ifdef __cplusplus
}
#endif
